In [2]:
import numpy as np


a = np.arange(16)

In [3]:
b = a + 1

In [5]:
a == 10

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False], dtype=bool)

Boolean Array 常常用于选择元素

In [6]:
b[a == 10]

array([11])

相同 shape 的数据做运算，是逐点做的

In [7]:
a * b

array([  0,   2,   6,  12,  20,  30,  42,  56,  72,  90, 110, 132, 156,
       182, 210, 240])

广播(broadcast) 是 numpy 和 pandas 中对于 universe function 常用的一种机制。
universe function 比如 +，
A + B 表示 A 和 B 逐点相加
如果 A, B 的 shape 相同那么当然没有问题。
但是如果 A, B 的 shape 不相同，在如下情况下也是可以计算的：
- A 的 shape 为 (a1, a2)
- B 的 shape 为 (b1, b2)
- 如果 a1 != b1, 那么 a1, b1 中有一个 为 1
- 如果 a2 != b2, 那么 a2, b2 中有一个为 1
- 输出结果的 shape 为 max(a1, b1), max(a2, b2)

In [2]:
# example_1

import numpy as np

a = np.arange(9)
a.shape = 3, 3
b = np.arange(3)
b.shape = 3, 1
c = a + b
print(c)

# example_2，这个例子很常见

a = np.arange(5)
b = np.arange(6)
a.shape = 5, -1
b.shape = -1, 6
c = a + b
print(c)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[0 1 2 3 4 5]
 [1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]
 [4 5 6 7 8 9]]
